%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# System.SaveAtlasToFile: "map"
# System.LoadAtlasFromFile: "map"

# Right Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 923.848388671875
Camera1.fy: 923.85546875
Camera1.cx: 647.532470703125
Camera1.cy: 361.49072265625
# distortion parameters
Camera1.k1: 0.00
Camera1.k2: 0.00
Camera1.p1: 0.00
Camera1.p2: 0.00

# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

Stereo.ThDepth: 10.0
Stereo.b: 0.0745

# Depth map values factor
# System.thFarPoints: 10.0
RGBD.DepthMapFactor: 1000.0

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data : [ 9.999220e-01, -8.723500e-03,  8.910490e-03,  2.050551e-02,
            8.718580e-03,  9.999620e-01,  5.914740e-04, -4.696043e-03,
           -8.915310e-03, -5.137420e-04,  9.999600e-01, -1.174969e-02,
            0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]


# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 1

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1e-3 # 5e-4 # rad/s^0.5
IMU.NoiseAcc: 1e-2 # 5e-3 # m/s^1.5
IMU.GyroWalk: 1e-4 # 5e-5 rad/s^1.5
IMU.AccWalk: 1e-3 # 5e-4 m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2500

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 16

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 5

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
