%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
# System.LoadAtlasFromFile: "MapEuRoCMH_StereoImu"

# The store file is created from the current session, if a file with the same name exists it is deleted
# System.SaveAtlasToFile: "MapEuRoCMH_StereoImu"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 2408.958299019289
Camera1.fy: 2407.4108025855985
Camera1.cx: 1217.202129402266
Camera1.cy: 1008.0805056355936

Camera1.k1: -0.10578994519289313
Camera1.k2: 0.09422229142179946
Camera1.p1: 0.0013657551176135007
Camera1.p2: 0.0014318564547443212

# Camera1.fx: 3493.6531503066567
# Camera1.fy: 3487.2085061501566
# Camera1.cx: 1994.2867290363158
# Camera1.cy: 1505.339855883075
# 
# Camera1.k1: -0.16223553731814372
# Camera1.k2: 0.15957995458066512
# Camera1.p1: -0.0006589441811486555
# Camera1.p2: -0.00225067440852858

# Camera1.width: 2448
# Camera1.height: 2048
# 
# Camera2.width: 4096
# Camera2.height: 3000

Camera.width: 2448
Camera.height: 2048

# Camera frames per second 
Camera.fps: 6

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
# Stereo.ThDepth: 60.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [-0.6859657 ,  0.00162735,  0.72763206,  0.02162638,
         -0.01112346, -0.9999041 , -0.00825022,  0.15438753,
          0.72754885, -0.01375315,  0.68591801, -0.05074615,
          0.        ,  0.        ,  0.        ,  1.        ]

# Transformation from camera 1 to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 9.999037e-01,  2.660697e-03, -1.361876e-02, -1.026700e-02,
          2.651117e-03, -9.999962e-01, -7.214026e-04,  9.724500e-02,
         -1.362063e-02,  6.852282e-04, -9.999070e-01, -1.914182e-01,
          0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]

# Transformation from camera 2 to body-frame (imu)
# IMU.T_b_c1: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: f
#   data: [-6.958376e-01, -8.459513e-04,  7.181987e-01,  1.245917e-02,
#           8.779987e-03,  9.999146e-01,  9.684400e-03, -5.704800e-02,
#          -7.181455e-01,  1.304454e-02, -6.957707e-01, -1.408656e-01,
#           0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]

# IMU noise
IMU.NoiseGyro: 6.5e-4
IMU.NoiseAcc: 6.0e-3
IMU.GyroWalk: 5.6e-4
IMU.AccWalk: 6.3e-4
IMU.Frequency: 400.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 10
ORBextractor.minThFAST: 3

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -1.7
Viewer.ViewpointZ: 0.8
Viewer.ViewpointF: -500.0
Viewer.imageViewScale: 1.0

